name: Build x86 Binary

on:
  push:
    branches:
      - master
    tags:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build x86 binary
        run: |
          mkdir -p build
          GOOS=linux
          GOARCH=386
          OUTPUT_NAME=my_binary
          env GOOS=$GOOS GOARCH=$GOARCH go build -o build/$OUTPUT_NAME

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: x86-binary
          path: build/
          retention-days: 1
